;; Copyright (c) 2026 SnapKittyWest. Ahmad Ali Parr, Bel Esprit D'Accord Irrevocable Trust.
;; SPDX-License-Identifier: AGPL-3.0-or-later
;; SOVEREIGN DEED: DEVFLOW_FINANCE_ACCOUNT_REGISTRY-085
;; Account registry with deterministic fixed-point arithmetic

(module
  (memory (export "memory") 2)

  (global $account_count (mut i32) (i32.const 0))
  (global $ACCOUNT_BASE_ADDR i32 (i32.const 1024))
  (global $ACCOUNT_ENTRY_SIZE i32 (i32.const 16))

  (func $find_account_index (param $id_hash i64) (result i32)
    (local $i i32)
    (local $addr i32)
    (local.set $i (i32.const 0))
    (block $not_found
      (loop $search
        (br_if $not_found (i32.ge_s (local.get $i) (global.get $account_count)))
        (local.set $addr (i32.add (global.get $ACCOUNT_BASE_ADDR) (i32.mul (local.get $i) (global.get $ACCOUNT_ENTRY_SIZE))))
        (if (i64.eq (i64.load (local.get $addr)) (local.get $id_hash))
          (then (return (local.get $i)))
        )
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $search)
      )
    )
    (i32.const -1)
  )

  (func (export "create_account") (param $id_hash i64) (param $initial_balance i64) (result i32)
    (local $idx i32)
    (local $addr i32)
    (local.set $idx (call $find_account_index (local.get $id_hash)))
    (if (i32.ne (local.get $idx) (i32.const -1))
      (then (return (i32.const 0)))
    )
    (local.set $idx (global.get $account_count))
    (local.set $addr (i32.add (global.get $ACCOUNT_BASE_ADDR) (i32.mul (local.get $idx) (global.get $ACCOUNT_ENTRY_SIZE))))
    (i64.store (local.get $addr) (local.get $id_hash))
    (i64.store offset=8 (local.get $addr) (local.get $initial_balance))
    (global.set $account_count (i32.add (local.get $idx) (i32.const 1)))
    (i32.const 1)
  )

  (func (export "post_transaction") (param $from_id i64) (param $to_id i64) (param $amount i64) (result i32)
    (local $from_idx i32)
    (local $to_idx i32)
    (local $from_addr i32)
    (local $to_addr i32)
    (local $from_bal i64)
    (local $to_bal i64)
    (if (i64.le_s (local.get $amount) (i64.const 0))
      (then (return (i32.const 0)))
    )
    (local.set $from_idx (call $find_account_index (local.get $from_id)))
    (local.set $to_idx (call $find_account_index (local.get $to_id)))
    (if (i32.eq (local.get $from_idx) (i32.const -1)) (then (return (i32.const 0))))
    (if (i32.eq (local.get $to_idx) (i32.const -1)) (then (return (i32.const 0))))
    (local.set $from_addr (i32.add (global.get $ACCOUNT_BASE_ADDR) (i32.mul (local.get $from_idx) (global.get $ACCOUNT_ENTRY_SIZE))))
    (local.set $to_addr (i32.add (global.get $ACCOUNT_BASE_ADDR) (i32.mul (local.get $to_idx) (global.get $ACCOUNT_ENTRY_SIZE))))
    (local.set $from_bal (i64.load offset=8 (local.get $from_addr)))
    (local.set $to_bal (i64.load offset=8 (local.get $to_addr)))
    (if (i64.lt_s (local.get $from_bal) (local.get $amount))
      (then (return (i32.const 0)))
    )
    (i64.store offset=8 (local.get $from_addr) (i64.sub (local.get $from_bal) (local.get $amount)))
    (i64.store offset=8 (local.get $to_addr) (i64.add (local.get $to_bal) (local.get $amount)))
    (i32.const 1)
  )

  (func (export "get_balance") (param $id_hash i64) (result i64)
    (local $idx i32)
    (local $addr i32)
    (local.set $idx (call $find_account_index (local.get $id_hash)))
    (if (i32.eq (local.get $idx) (i32.const -1))
      (then (return (i64.const 0)))
    )
    (local.set $addr (i32.add (global.get $ACCOUNT_BASE_ADDR) (i32.mul (local.get $idx) (global.get $ACCOUNT_ENTRY_SIZE))))
    (i64.load offset=8 (local.get $addr))
  )
)
