-- Event store for replayable events
CREATE TABLE EVENT_STORE (
    EVENT_ID        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EVENT_TYPE      VARCHAR(128) NOT NULL,
    AGGREGATE_ID    VARCHAR(128),
    AGGREGATE_TYPE  VARCHAR(64),
    PAYLOAD         BLOB(2M),
    OCCURRED_AT     TIMESTAMP NOT NULL,
    SEQUENCE_NUM    BIGINT NOT NULL,
    PROCESSED       CHAR(1) NOT NULL DEFAULT 'N',
    UNIQUE (SEQUENCE_NUM)
);

CREATE INDEX IDX_EVENT_STORE_SEQ ON EVENT_STORE(SEQUENCE_NUM);

-- Rail submissions and notifications
CREATE TABLE RAIL_SUBMISSIONS (
    SUBMISSION_ID   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RAIL_CODE       VARCHAR(16) NOT NULL,
    PAYMENT_ID      BIGINT,
    TRANSACTION_ID  BIGINT,
    STATUS          VARCHAR(32) NOT NULL, -- CREATED, SUBMITTED, ACKED, SETTLED, FAILED
    EXTERNAL_REF    VARCHAR(128),
    CREATED_AT      TIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP NOT NULL
);

CREATE TABLE RAIL_NOTIFICATIONS (
    NOTIF_ID        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SUBMISSION_ID   BIGINT NOT NULL,
    RAIL_CODE       VARCHAR(16) NOT NULL,
    TYPE            VARCHAR(64) NOT NULL, -- SETTLEMENT, RETURN, ACK
    PAYLOAD         BLOB(2M),
    RECEIVED_AT     TIMESTAMP NOT NULL,
    FOREIGN KEY (SUBMISSION_ID) REFERENCES RAIL_SUBMISSIONS(SUBMISSION_ID)
);

-- End of day run log
CREATE TABLE EOD_RUNS (
    RUN_ID          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RUN_DATE        DATE NOT NULL,
    STARTED_AT      TIMESTAMP NOT NULL,
    FINISHED_AT     TIMESTAMP,
    STATUS          VARCHAR(32) NOT NULL, -- RUNNING, COMPLETED, FAILED
    SUMMARY         CLOB
);

-- Concurrency test harness results
CREATE TABLE INVARIANT_TEST_RESULTS (
    TEST_ID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RUN_AT          TIMESTAMP NOT NULL,
    TOTAL_JOURNALS  BIGINT,
    IMBALANCES      BIGINT,
    DETAILS         CLOB
);
